from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

class ApplicantForm(BaseModel):
    full_name: Optional[str] = Field(None, description="Masked full name")
    national_id: Optional[str] = Field(None, description="Masked national ID")

    age: int
    employment_type: str

    monthly_income_declared: float
    monthly_expenses_declared: float

    late_payments_declared: int
    sector: str
    other_loans_count: int

class LoanRequest(BaseModel):
    loan_amount: float
    term_months: int

    product: str
    purpose: str
    collateral_declared: Optional[str] = None

class DocumentRef(BaseModel):
    doc_id: str
    type: str  # ID_CARD | BANK_STATEMENT | CONTRACT
    uri: str

class ApplicationPackage(BaseModel):
    case_id: Optional[str] = Field(
        None, description="Generated by backend"
    )

    submitted_at: Optional[datetime] = Field(
        None, description="Submission timestamp"
    )

    applicant_form: ApplicantForm
    loan_request: LoanRequest
    documents: List[DocumentRef]
